SELECT A2.AUTHOR_ID
     , A2.AUTHOR_NAME
     , A1.CATEGORY
     , SUM(A1.PRICE * A3.SUM_SALES) AS TOTAL_SALES
  FROM BOOK A1
     , AUTHOR A2
     , (SELECT BOOK_ID
             , SUM(SALES) AS SUM_SALES
          FROM BOOK_SALES
         WHERE TO_CHAR(SALES_DATE, 'YYYYMM') = '202201'
         GROUP BY BOOK_ID) A3
  WHERE A1.AUTHOR_ID = A2.AUTHOR_ID
    AND A1.BOOK_ID = A3.BOOK_ID
  GROUP BY A2.AUTHOR_ID
         , A2.AUTHOR_NAME
         , A1.CATEGORY
  ORDER BY A2.AUTHOR_ID, A1.CATEGORY DESC;