SELECT A.PRODUCT_ID
     , A.PRODUCT_NAME
     , (A.PRICE * B.TOTAL_AMOUNT) AS TOTAL_SALES
  FROM FOOD_PRODUCT A
     , (SELECT PRODUCT_ID
             , SUM(AMOUNT) AS TOTAL_AMOUNT
          FROM FOOD_ORDER
         WHERE TO_CHAR(PRODUCE_DATE, 'YYYYMM') = '202205'
         GROUP BY PRODUCT_ID) B
 WHERE A.PRODUCT_ID = B.PRODUCT_ID
 ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID;