SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, LEFT(R.CREATED_DATE, 10)
FROM USED_GOODS_BOARD AS B, USED_GOODS_REPLY AS R
WHERE LEFT(B.CREATED_DATE, 7) = '2022-10' AND B.BOARD_ID = R.BOARD_ID
ORDER BY R.CREATED_DATE ASC, TITLE ASC