SELECT A.FLAVOR
  FROM FIRST_HALF A
     , (SELECT FLAVOR
             , SUM(TOTAL_ORDER) AS T_ORDER
          FROM JULY
         GROUP BY FLAVOR) B
 WHERE A.FLAVOR = B.FLAVOR
 ORDER BY (A.TOTAL_ORDER + B.T_ORDER) DESC
 FETCH FIRST 3 ROWS ONLY